### ISSUE TITLE
API Design

### ISSUE THREAD

**Issue by dcherman** [dcherman/argocd-configmap-hook#2]
The original idea when this was going to be implemented inside of ArgoCD was to provide something like 

```yaml
helm:
  valuesFrom:
  - configMapKeyRef:
      # Name of the config map
      name: default-values  # mandatory
      # Namespace of the config map
      namespace: my-ns      # optional; defaults to HelmRelease namespace
      # Key in the config map to get the values from
      key: values.yaml      # optional; defaults to values.yaml
      # If set to true successful retrieval of the values file is no
      # longer mandatory
      optional: false       # optional; defaults to false
```

If that looks familiar, it's because it's the identical API that the `HelmRelease` release in the helm operator provides.

According to https://kubernetes.io/blog/2019/03/21/a-guide-to-kubernetes-admission-controllers/, mutating admission controllers have the opportunity to modify the contents of incoming objects before they're subject to object schema validation

![image](https://user-images.githubusercontent.com/976608/78254558-1c928d80-74c4-11ea-88a4-26fdfabbf207.png)

The idea is that we can introduce/use new fields into the existing Application CR so long as we remove them in the mutating admission controller before they're passed off for validation.  By doing that, we can emulate the approach that we would take if this feature were to be put into ArgoCD core.

In order to validate that approach, I'm going to create a simple CRD/Webhook on a local cluster to ensure that the idea actually works and will report back here.
